import os
import itplz.core


def run(top_file, topology, mdls, out_file, verbose=False):
    def_map = itplz.core.DefMapping(topology, mdls)
    incs = def_map.get_includes()

    with open(out_file, "w") as f:
        f.write(f"; includes generated by itplz\n")
        for inc in incs.mapping:
            i_path = os.path.normpath(os.path.relpath(inc, os.path.dirname(out_file)))
            f.write(f'#include "{i_path}" ; {", ".join(incs.mapping[inc])}\n')

        with open(top_file, "r") as top_f:
            for line in top_f.readlines():
                if not line.startswith("#include"):
                    f.write(line)
