import sys
import itplz.mol_def
import itplz.topology
import argparse
import pathlib
from collections import defaultdict
parser = argparse.ArgumentParser(
    prog="itplz",
    description="Pleasing tools for working with ITP and gromacs files",
    epilog="Good luck!",
)

subparsers = parser.add_subparsers(dest="sub_name")
moltypes = subparsers.add_parser(
    "moltypes", help="print out all molecule types covered by the set of ITP files"
)
moltypes.add_argument(
    "--directories",
    nargs="*",
    default=[],
    help="Loads any file with .itp file in the directory and all subdirectories",
)
moltypes.add_argument("--files", nargs="*", default=[])


print_include = subparsers.add_parser(
    "print-includes", help="Generate an include string for a set of moltypes"
)
print_include.add_argument("--directories", nargs="*", default=[])
print_include.add_argument("--files", nargs="*", default=[])
print_include.add_argument("--moltypes", nargs="+", default=[])

add_include = subparsers.add_parser(
    "add-includes", help="Writes a topology file with additional includes"
)
add_include.add_argument("--directories", nargs="*", default=[], help="Directories to find ITP files")
add_include.add_argument("--files", nargs="*", default=[], help="List of ITP files")
add_include.add_argument("--top", help="Input topology file") 



check_top = subparsers.add_parser(
    "check-top", help="Check a topology file for issues. Can be optionally run with extra ITP files to check outcome."
)
check_top.add_argument("--directories", nargs="*", default=[])
check_top.add_argument("--files", nargs="*", default=[])
check_top.add_argument("--top")


def run_moltypes(directories=[], files=[]):
    mdls = itplz.mol_def.MolDefLoader()
    for d in directories:
        mdls.load_directory(d)
    for f in files:
        mdls.load_itp_file(f)

    for ds in mdls.mol_defs.values():
        for d in ds:
            print(f"{d.name:<10}{d.file}:{d.line_num}")
    


def create_includes(mol_defs, molecules):
    """Given a list of molecules, generate the include statement for them."""
    def_to_molecules = defaultdict(list)
    for mol in molecules:
        def_to_molecules[mol_defs[mol][0].file].append(mol)

    for itp in def_to_molecules:
        print(f'#include "{itp}" ; {",".join(def_to_molecules[itp])}')



def run_print_includes(directories=[], files=[], moltypes=[]):
    mdls = itplz.mol_def.MolDefLoader()
    for d in directories:
        mdls.load_directory(d)
    for f in files:
        mdls.load_itp_file(f)

    print("; Inlcudes generated by itplz")
    create_includes(mdls.mol_defs, moltypes)


# Not currently used. Would be nice to print
# things as a tree, as ITPs can include other ITPs for example.
def wip_print_topology_tree(top):
    stack = [top.filename]
    depth = 0
    dpad = "   "
    defs = [d for md in top.mol_defs.mol_defs.values() for d in md]
    while len(stack) > 0:
        curr_file = stack.pop()
        pad = dpad * len(stack)
        print(f"          {pad} {curr_file}")
        for d in defs:
            if d.name in top.moleculetypes:
                if d.file == curr_file:
                    print(f"{d.name:<10}{pad + dpad} defined line:{d.line_num}")
        stack += top.mol_defs.include_tree[curr_file]


        
def run_add_includes(top, directories=[], files=[]):
    topology = itplz.topology.Topology(top)
    mdls = itplz.mol_def.MolDefLoader()
    for d in directories:
        mdls.load_directory(d)
    for f in files:
        mdls.load_itp_file(f)
    last_include =  max(topology.mol_defs.include_lines.values())
    with open(top, 'r') as f:
        for idx, line in enumerate(f.readlines()):
            print(line[:-1])
            if idx == last_include:
                print('; added by itplz')
                create_includes(mdls.mol_defs, [f for f in topology.moleculetypes if not topology.mol_defs.contains(f)])
                

    

def run_check_top(top, extra_directories=[], extra_files=[]):
    topology = itplz.topology.Topology(top)
    extra_mdls = itplz.mol_def.MolDefLoader()
    for d in extra_directories:
        extra_mdls.load_directory(d)
    for f in extra_files:
        extra_mdls.load_itp_file(f)
    not_in_top = []
    not_in_extras = []
    print("✔  Molecule types which have moleculartype definitions already")
    for mt in topology.moleculetypes:
        if topology.mol_defs.contains(mt):
            include = topology.mol_defs.get(mt)
            print(f"{mt:<10} {include.file}:{include.line_num}")
        else:
            not_in_top.append(mt)
    print()
    print("# Molecules which have types defined in extra itp files")
    for mt in not_in_top:
        if extra_mdls.get(mt) is not None:
            include = extra_mdls.get(mt)
            print(f"{mt:<10} {include.file}:{include.line_num}")
        else:
            not_in_extras.append(mt)
    print()
    print("# Molecules which lack a definition")
    for mt in not_in_extras:
        print(f"{mt}") 

    print()
    print("# Includes which could not be loaded")
    for inc in topology.mol_defs.failed_includes:
        print(f"{inc}")

    print("# Molecules with multiple definitions")
    for mt in topology.moleculetypes:
        if extra_mdls.contains(mt):
            if len(extra_mdls.mol_defs[mt]) > 1:
                print(f"{mt} is defined in:")
                for f in extra_mdls.mol_defs[mt]:
                    print(f"  {f.file}:{f.line_num}")



def main():
    args = parser.parse_args()
    if args.sub_name == "moltypes":
        run_moltypes(args.directories, args.files)

    if args.sub_name == "print-includes":
        run_print_includes(args.directories, args.files, args.moltypes)

    if args.sub_name == "check-top":
        run_check_top(args.top, args.directories, args.files)

    if args.sub_name == "add-includes":
        run_add_includes(args.top, args.directories, args.files)
